### ISSUE TITLE
Implementar background no board

### ISSUE THREAD

**Issue by walber-vaz** [valmisson/Trellu#1]
Seria legal poder colocar cor, tanto no card quanto no background ai fica massa eu tô usando ele no lugar do trello, ficou muito bom :1st_place_medal:

**Comment by valmisson** [comment]
Obrigado, já tinha em mente implementar a cor no background e realmente vai ficar mais legal, Sobre a  cor nos cards você esta se referindo as etiquetas que existe no trello ?

**Comment by valmisson** [comment]
Obrigado, já tinha em mente implementar a cor no background e realmente vai ficar mais legal, Sobre a cor nos cards você esta se referindo as etiquetas que existe no trello?

**Comment by walber-vaz** [comment]
Isso mesmo é outra também podia ter opção pina aquela de fixar ele. :+1:

**Comment by valmisson** [comment]
Implementei o background nos boards e fiz alguns ajuste

**Comment by walber-vaz** [comment]
Ok ficou muito bom. Vir também Hum bug no pwa não sei se você já percebeu, quando você clicar na intiqueta para editar ela demora muito pra aparecer as vezes tem que clicar 2 ou 3 vezes. Será que poder ser a área de clique. Que está muito pequena.

**Comment by valmisson** [comment]
Não encontrei esse bug, nos navegadores que teste está normal. Qual o navegador você está usando ?

**Comment by walber-vaz** [comment]
Tô usando Chrome no Android

**Comment by valmisson** [comment]
Ok, na versão mobile existe uns bug no drag-drog mesmo. já estou corrigindo. Obrigado pelo feedback.

**Comment by valmisson** [comment]
Na versão mobile existe uns bug no drag-drog mesmo. já estou corrigindo. Obrigado pelo feedback.

**Comment by walber-vaz** [comment]
Ok muito bom projeto. Continue que vai longe. Fechando issue
